version: "3"
services:
  docker-nginx:
    image: nginx:alpine
    container_name: docker-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx/log:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - docker-php
    links:
      - docker-php
    networks: 
      - docker-net

  docker-go:
    image: golang:1.12.0
    container_name: docker-go
    ports:
      - 8088:8088
    volumes:
      - ./go:/go
    tty: true
    networks: 
      - docker-net

  docker-php:
    build: ./php
    container_name: docker-php
    volumes:
      - ./php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./www:/var/www/html
      - ./php/log:/usr/local/var/log
      - ./php/supervisor/conf.d:/etc/supervisor/conf.d
      - ./php/supervisor/log:/var/log/supervisor
    networks: 
      - docker-net

  docker-mysql:
    image: mysql:8
    container_name: docker-mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
    networks:
      - docker-net
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

  docker-mongo:
    image: mongo
    container_name: docker-mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data/:/data/db/
    networks:
      - docker-net
      
  docker-rabbitmq:
    image: rabbitmq:3-management
    container_name: docker-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456
    networks: 
      - docker-net

  docker-redis:
    image: redis:5.0
    container_name: docker-redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    # 自定义配置启动失败，后期解决 
    #   - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    # command:
    #   redis-server /usr/local/etc/redis/redis.conf
    networks: 
      - docker-net
networks: 
  docker-net: